### ISSUE TITLE
Website responsiveness

### ISSUE THREAD

**Issue by saehaana** [saehaana/saehaana.github.io#4]
all text should be adjusted to both web and mobile 

- narrowing/widening screen should push name, title, and navbar down or up as well as adjust font size
- shrinking/expanding screen vertically should not alter the background image but rather hide or show it
    - name, title, and navbar should only be altered slightly by this adjustment since it is in the top left corner

**Comment by sambhavx-x** [comment]
Hello!! I am new to open source ,but I think I can help you with this issue. Can you let me try and assign this to me ? Thank you for your time .

**Comment by Rengkat** [comment]
Hello, I can help

**Comment by saehaana** [comment]
Hey guys, thanks for wanting to help but this is supposed to be a private project. However I can't set it to private since GitHub Pages requires free users to have the repository set to public for free deployment! Thank you again for wanting to contribute.
